### ISSUE TITLE
Help me 

### ISSUE THREAD

**Issue by jeffersonveloso** [josephktcheung/test-typeorm#1]
Hi bro, how you doing ? I have issues with @Tree('closure-table') on "typeorm": "^0.2.45".

When i tried to do a crud of insert the typeorm threw a error below.

My Table
`@Entity({
  name: 'field',
  schema: 'public'
})
@Tree('closure-table')
export class FieldModel extends BaseEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column({ type: 'varchar', nullable: false, unique: true })
  zohoId: string;

  @Column({ type: 'varchar', nullable: false })
  zohoField: string;

  @Column({ type: 'text', nullable: false })
  zohoAlias: string;

  @Column({ type: 'varchar', enum: ZohoTable, nullable: false })
  zohoTable: ZohoTable;

  @Column({ type: 'text', nullable: false })
  omieField: string;

  @Column({ type: 'varchar', nullable: true })
  omieAlias: string;

  @Column({ type: 'varchar', enum: OmieTable, nullable: false })
  omieTable: OmieTable;

  @Column({ type: 'varchar', nullable: false })
  type: string;

  @TreeChildren({ cascade: true })
  children?: FieldModel[];

  @TreeParent()
  parent?: FieldModel;
}`

`QueryFailedError: relation "public.field_closure" does not exist
api_1       |       at QueryFailedError.TypeORMError [as constructor] (/usr/src/api/src/error/TypeORMError.ts:7:9)
api_1       |       at new QueryFailedError (/usr/src/api/src/error/QueryFailedError.ts:9:9)
api_1       |       at PostgresQueryRunner.<anonymous> (/usr/src/api/src/driver/postgres/PostgresQueryRunner.ts:263:19)
api_1       |       at step (/usr/src/api/node_modules/tslib/tslib.js:143:27)
api_1       |       at Object.throw (/usr/src/api/node_modules/tslib/tslib.js:124:57)
api_1       |       at rejected (/usr/src/api/node_modules/tslib/tslib.js:115:69)
api_1       |       at processTicksAndRejections (node:internal/process/task_queues:96:5) {
api_1       |     query: 'INSERT INTO "public"."field_closure"("id_ancestor", "id_descendant") VALUES ($1, $2)',
api_1       |     parameters: [ 33, 33 ],
api_1       |     driverError: error: relation "public.field_closure" does not exist
api_1       |         at Parser.parseErrorMessage (/usr/src/api/node_modules/pg-protocol/src/parser.ts:369:69)
api_1       |         at Parser.handlePacket (/usr/src/api/node_modules/pg-protocol/src/parser.ts:188:21)
api_1       |         at Parser.parse (/usr/src/api/node_modules/pg-protocol/src/parser.ts:103:30)
api_1       |         at Socket.<anonymous> (/usr/src/api/node_modules/pg-protocol/src/index.ts:7:48)
api_1       |         at Socket.emit (node:events:526:28)
api_1       |         at addChunk (node:internal/streams/readable:315:12)
api_1       |         at readableAddChunk (node:internal/streams/readable:289:9)
api_1       |         at Socket.Readable.push (node:internal/streams/readable:228:10)
api_1       |         at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
api_1       |       length: 119,
api_1       |       severity: 'ERROR',
api_1       |       code: '42P01',
api_1       |       detail: undefined,
api_1       |       hint: undefined,
api_1       |       position: '13',
api_1       |       internalPosition: undefined,
api_1       |       internalQuery: undefined,
api_1       |       where: undefined,
api_1       |       schema: undefined,
api_1       |       table: undefined,
api_1       |       column: undefined,
api_1       |       dataType: undefined,
api_1       |       constraint: undefined,
api_1       |       file: 'parse_relation.c',
api_1       |       line: '1360',
api_1       |       routine: 'parserOpenTable'
api_1       |     },
api_1       |     length: 119,
api_1       |     severity: 'ERROR',
api_1       |     code: '42P01',
api_1       |     detail: undefined,
api_1       |     hint: undefined,
api_1       |     position: '13',
api_1       |     internalPosition: undefined,
api_1       |     internalQuery: undefined,
api_1       |     where: undefined,
api_1       |     schema: undefined,
api_1       |     table: undefined,
api_1       |     column: undefined,
api_1       |     dataType: undefined,
api_1       |     constraint: undefined,
api_1       |     file: 'parse_relation.c',
api_1       |     line: '1360',
api_1       |     routine: 'parserOpenTable'
api_1       |   }
api_1       | }
`

**Comment by josephktcheung** [comment]
Hi,

I've not been using typeorm recently, however from what I read from your error message `public.field_closure` may not exist in your database. Do you have such table created?

**Comment by jeffersonveloso** [comment]
> Hi,
> 
> I've not been using typeorm recently, however from what I read from your error message `public.field_closure` may not exist in your database. Do you have such table created?

I didn't have this table created. I only added the decorator on FieldModel and tried to save the data.

<img width="1297" alt="Captura de Tela 2022-07-06 às 17 02 09" src="https://user-images.githubusercontent.com/32569611/177831071-d8650caa-e966-4e2b-97f8-55c048c19bd6.png">
<img width="852" alt="Captura de Tela 2022-07-06 às 17 03 46" src="https://user-images.githubusercontent.com/32569611/177831082-9e96b076-c2ed-46d1-9e95-16d62bfba695.png">
<img width="845" alt="Captura de Tela 2022-07-06 às 17 03 56" src="https://user-images.githubusercontent.com/32569611/177831086-7f6f18c7-4a9d-4111-b992-cea016534fd1.png">

**Comment by josephktcheung** [comment]
> > Hi,
> 
> > 
> 
> > I've not been using typeorm recently, however from what I read from your error message `public.field_closure` may not exist in your database. Do you have such table created?
> 
> 
> 
> I didn't have this table created. I only added the decorator on FieldModel and tried to save the data.
> 
> 
> 
> <img width="1297" alt="Captura de Tela 2022-07-06 às 17 02 09" src="https://user-images.githubusercontent.com/32569611/177831071-d8650caa-e966-4e2b-97f8-55c048c19bd6.png">
> 
> <img width="852" alt="Captura de Tela 2022-07-06 às 17 03 46" src="https://user-images.githubusercontent.com/32569611/177831082-9e96b076-c2ed-46d1-9e95-16d62bfba695.png">
> 
> <img width="845" alt="Captura de Tela 2022-07-06 às 17 03 56" src="https://user-images.githubusercontent.com/32569611/177831086-7f6f18c7-4a9d-4111-b992-cea016534fd1.png">
> 
> 

I think you can generate a migration. typeorm will find any missing table / relation and generate a migration file for you. 

https://typeorm.io/migrations#generating-migrations

**Comment by jeffersonveloso** [comment]
Thanks bro, the comand to generate a migration by Entity generate the closure-table. When I use the migration api to create my migration manually it's necessary to create closure-table manually too.

**Comment by jeffersonveloso** [comment]
I discovered the problem. When you use migrations and you didn't generate the migration using the migration:generate command the typeorm doesn't create the closure-table automatically when you add the @Tree decorator. You need to either create the closure-table manually or run the migration:generate command to create the closure-table for you.
